/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.categoryPage;

import java.awt.Color;
import java.net.URISyntaxException;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;

/**
 *
 * @author Kind
 */
public class CategoryManage extends inventory.myClasses.MyJPanel {

    /**
     * Creates new form CategoryManage
     */
    public CategoryManage() {
        super();
        LoadData();
    }
    
    @Override
    public void setComponetsColor(Color transparent){
        
        this.categoryNameScrollPane.setBackground(transparent);
        this.categoryNameList.setBackground(transparent);

        this.descriptionScrollPane.setBackground(transparent);
        this.descriptionTextPane.setBackground(transparent);
        
        this.registerButton.setBackground(transparent);
        this.editButton.setBackground(transparent);
        this.dropButton.setBackground(transparent);
        this.backButton.setBackground(transparent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @Override
    public void LoadData(){
        list = new ArrayList<String>();
        pane = new ArrayList<String>();
        id = new ArrayList<Integer>();
        
        this.descriptionTextPane.setText("");
        
        try {
            ResultSet rs = null;
            
            rs = inventory.core.DBConnection.executeQuery("SELECT * FROM inventory.category order by name;");
            
            if(rs != null){
                while(rs.next()){
                    if(rs.getInt("disable_id") != 1){
                        continue;
                    }
                    list.add(rs.getString("name"));
                    pane.add(rs.getString("description"));
                    id.add(rs.getInt("id"));
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(CategoryManage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.categoryNameList.setListData(list.toArray());
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoryNameScrollPane = new javax.swing.JScrollPane();
        categoryNameList = new javax.swing.JList();
        descriptionScrollPane = new javax.swing.JScrollPane();
        descriptionTextPane = new inventory.myClasses.MyTextPane();
        backButton = new inventory.myClasses.MyButton();
        editButton = new inventory.myClasses.MyButton();
        dropButton = new inventory.myClasses.MyButton();
        registerButton = new inventory.myClasses.MyButton();

        categoryNameList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoryNameListMouseClicked(evt);
            }
        });
        categoryNameList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                categoryNameListValueChanged(evt);
            }
        });
        categoryNameScrollPane.setViewportView(categoryNameList);

        descriptionTextPane.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        descriptionTextPane.setEnabled(false);
        descriptionScrollPane.setViewportView(descriptionTextPane);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        dropButton.setText("Drop");
        dropButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropButtonActionPerformed(evt);
            }
        });

        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(categoryNameScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dropButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(dropButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(backButton))
                    .addComponent(categoryNameScrollPane, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionScrollPane, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void categoryNameListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryNameListMouseClicked
        // TODO add your handling code here:
        //System.out.println(this.categoryNameList.getSelectedIndex());
        this.descriptionTextPane.setText(this.pane.get(this.categoryNameList.getSelectedIndex()));
        if(this.categoryNameList.getSelectedIndex() >= 0 && evt.getClickCount() == 2){
            inventory.categoryPage.CategoryEdit p = new inventory.categoryPage.CategoryEdit();
            p.setEditConfig(id.get(this.categoryNameList.getSelectedIndex()), list.get(this.categoryNameList.getSelectedIndex()), pane.get(this.categoryNameList.getSelectedIndex()));
            
            if(inventory.core.ProjectBOMStockMain.display != null){
                inventory.core.ProjectBOMStockMain.display.dispose();
            }
            inventory.core.ProjectBOMStockMain.display = new inventory.core.ShowingFrame(p, "CategoryEdit");
            inventory.core.ProjectBOMStockMain.display.setVisible(true);
        }
    }//GEN-LAST:event_categoryNameListMouseClicked

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        if(inventory.core.ProjectBOMStockMain.display != null){
            inventory.core.ProjectBOMStockMain.display.dispose();
        }
        inventory.core.ProjectBOMStockMain.setPage(inventory.core.ProjectBOMStockMain.PageList.indexOf("AdminMain"));
    }//GEN-LAST:event_backButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        /*
        if(this.categoryNameList.getSelectedIndex()>=0 && this.categoryNameList.getSelectedIndex() < list.size()){
            inventory.core.ProjectBOMStockMain.setPage(inventory.core.ProjectBOMStockMain.PageList.indexOf("CategoryEdit"));
            ((inventory.categoryPage.CategoryEdit)inventory.core.ProjectBOMStockMain.getPage(inventory.core.ProjectBOMStockMain.PageList.indexOf("CategoryEdit"))).setEditConfig(id.get(this.categoryNameList.getSelectedIndex()), list.get(this.categoryNameList.getSelectedIndex()), pane.get(this.categoryNameList.getSelectedIndex()));
        }f1
        */
        if(this.categoryNameList.getSelectedIndex() >= 0){
            inventory.categoryPage.CategoryEdit p = new inventory.categoryPage.CategoryEdit();
            p.setEditConfig(id.get(this.categoryNameList.getSelectedIndex()), list.get(this.categoryNameList.getSelectedIndex()), pane.get(this.categoryNameList.getSelectedIndex()));
            
            if(inventory.core.ProjectBOMStockMain.display != null){
                inventory.core.ProjectBOMStockMain.display.dispose();
            }
            inventory.core.ProjectBOMStockMain.display = new inventory.core.ShowingFrame(p, "CategoryEdit");
            inventory.core.ProjectBOMStockMain.display.setVisible(true);
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void dropButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropButtonActionPerformed
        // TODO add your handling code here:
        /*
        int dialogResult = JOptionPane.showConfirmDialog (this, "Would You Like to Delete? Are you Sure?!","Warning",JOptionPane.YES_NO_OPTION);
        
        if(dialogResult == JOptionPane.YES_OPTION){
            inventory.core.DBConnection.updateQuery("DELETE FROM `inventory`.`category` WHERE `id`='"+id.get(this.categoryNameList.getSelectedIndex())+"';");
            this.LoadData();
        }
        */
        inventory.core.ProjectBOMStockMain.dropAndDisable(this, this.id, this.categoryNameList, inventory.core.ProjectBOMStockMain.table_type.indexOf("Category"));
    }//GEN-LAST:event_dropButtonActionPerformed

    private void categoryNameListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_categoryNameListValueChanged
        // TODO add your handling code here:
        if(this.categoryNameList == null){
            return;
        }
        if(this.descriptionTextPane == null){
            return;
        }
        if(this.pane == null){
            return;
        }
        
        
        if(this.categoryNameList.getSelectedIndex()>=0 && this.categoryNameList.getSelectedIndex() < pane.size()){
            this.descriptionTextPane.setText(this.pane.get(this.categoryNameList.getSelectedIndex()));
            
            this.updateUI();
        }
    }//GEN-LAST:event_categoryNameListValueChanged

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        //inventory.core.ProjectBOMStockMain.setPage(inventory.core.ProjectBOMStockMain.PageList.indexOf("CategoryRegister"));
        inventory.categoryPage.CategoryRegister p = new inventory.categoryPage.CategoryRegister();
        if(inventory.core.ProjectBOMStockMain.display != null){
            inventory.core.ProjectBOMStockMain.display.dispose();
        }
        inventory.core.ProjectBOMStockMain.display = new inventory.core.ShowingFrame(p, "CategoryRegister");
        inventory.core.ProjectBOMStockMain.display.setVisible(true);
    }//GEN-LAST:event_registerButtonActionPerformed
    
    public void findAndSetSelectedItem(String name){
        this.categoryNameList.setSelectedIndex(this.list.indexOf(name));
    }
    
    private ArrayList<String> list = null;
    private ArrayList<String> pane = null;
    private ArrayList<Integer> id = null;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JList categoryNameList;
    private javax.swing.JScrollPane categoryNameScrollPane;
    private javax.swing.JScrollPane descriptionScrollPane;
    private javax.swing.JTextPane descriptionTextPane;
    private javax.swing.JButton dropButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton registerButton;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void myInitComponents() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        this.initComponents();
    }
}
