/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.reportPage;


import inventory.core.ProjectBOMStockMain;
import java.util.Date;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Liz
 */
public class reportMain extends javax.swing.JPanel {
    private Date startDate = null;
    private Date expireDate = null;
//    private Integer categoryId = null;
//    private Integer code = null;
//    private Integer currentInventory = null;
//    private String nameList = null; 
   
   
    /**
     * Creates new form reportMain
     */
    public reportMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Apply = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        ExpireDateButton = new javax.swing.JButton();
        startDateTextField = new javax.swing.JTextField();
        startDateButton = new javax.swing.JButton();
        expireDateTextField = new javax.swing.JTextField();
        dateRange = new javax.swing.JLabel();

        Apply.setText("Apply");
        Apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyActionPerformed(evt);
            }
        });

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        ExpireDateButton.setText("To");
        ExpireDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpireDateButtonActionPerformed(evt);
            }
        });

        startDateButton.setText("From");
        startDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDateButtonActionPerformed(evt);
            }
        });

        expireDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expireDateTextFieldActionPerformed(evt);
            }
        });

        dateRange.setText("Date Range");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(Back))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(48, 48, 48)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(dateRange)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(ExpireDateButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(startDateButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .add(26, 26, 26)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(startDateTextField)
                            .add(expireDateTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(Apply)
                .add(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(22, 22, 22)
                .add(dateRange, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(startDateButton)
                    .add(startDateTextField))
                .add(30, 30, 30)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(ExpireDateButton)
                    .add(expireDateTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 76, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Apply)
                    .add(Back))
                .add(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void clearElements(){
   //     categoryId = null;
   //     nameList = null;
   //     code = null;
   //     currentInventory = null;
        expireDate = null;
        startDate = null;
        
        startDateTextField.setText("");
        expireDateTextField.setText("");
    }
        
   
    private void ApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyActionPerformed
        // TODO add your handling code here:
        Date sDate = startDate;
        Date exDate = expireDate;
      
        if( exDate.getTime() - sDate.getTime() > 0){    
        if(inventory.core.ProjectBOMStockMain.display != null){
            inventory.core.ProjectBOMStockMain.display.dispose();
        }
        inventory.core.ProjectBOMStockMain.setPage(inventory.core.ProjectBOMStockMain.PageList.indexOf("reportShow"));
        ((reportShow)ProjectBOMStockMain.getPage(inventory.core.ProjectBOMStockMain.PageList.indexOf("reportShow"))).LoadData(startDate, expireDate);
 //       LoadData(startDate, expireDate);
        }
        else {
             JOptionPane.showMessageDialog(this, "Apply Fail ","Warning",JOptionPane.OK_OPTION);
        }
        
    
 
    }//GEN-LAST:event_ApplyActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
          if(inventory.core.ProjectBOMStockMain.display != null){
            inventory.core.ProjectBOMStockMain.display.dispose();
        }
        inventory.core.ProjectBOMStockMain.setPage(inventory.core.ProjectBOMStockMain.PageList.indexOf("AdminMain"));
        clearElements();
    }//GEN-LAST:event_BackActionPerformed

    private void ExpireDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpireDateButtonActionPerformed
        // TODO add your handling code here:
        Date utilDate = null;
        if(this.expireDate != null){
            inventory.core.DateChooser dc = new inventory.core.DateChooser(new JDialog());
            utilDate = dc.select(this.expireDate);

        }else{
            utilDate =  new inventory.core.DateChooser(new JDialog()).select();
        }
        if(utilDate != null){
            java.sql.Date date = new java.sql.Date(utilDate.getTime());
            if(date != null){
                this.expireDate = date;
            }
        }
        
        if(this.expireDate != null){
            this.expireDateTextField.setText(this.expireDate.toString());    
        }
        
           if(this.expireDate != null){
            System.out.println(this.expireDate.toString());
            
        }
    }//GEN-LAST:event_ExpireDateButtonActionPerformed

    private void startDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDateButtonActionPerformed
        // TODO add your handling code here:
     Date utilDate = null;
        if(this.startDate != null){
            inventory.core.DateChooser dc = new inventory.core.DateChooser(new JDialog());
            utilDate = dc.select(this.startDate);
//            utilDate =  dc.select();
        }else{
            utilDate =  new inventory.core.DateChooser(new JDialog()).select();
        }
        if(utilDate != null){
            java.sql.Date date = new java.sql.Date(utilDate.getTime());
            if(date != null){
                this.startDate = date;
            }
        }
        
        if(this.startDate != null){
            this.startDateTextField.setText(this.startDate.toString());    
        }
        
        if(this.startDate != null){
            System.out.println(this.startDate.toString());
            
        }
    }//GEN-LAST:event_startDateButtonActionPerformed

    private void expireDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expireDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expireDateTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apply;
    private javax.swing.JButton Back;
    private javax.swing.JButton ExpireDateButton;
    private javax.swing.JLabel dateRange;
    private javax.swing.JTextField expireDateTextField;
    private javax.swing.JButton startDateButton;
    private javax.swing.JTextField startDateTextField;
    // End of variables declaration//GEN-END:variables
}
